services:
  backend:
    image: fbtpbot-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Saratov
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
      - ./brains:/app/brains:ro
      - ./templates:/app/templates:ro
    restart: unless-stopped

  tg-bot:
    image: fbtpbot-backend:latest
    environment:
      - TZ=Europe/Saratov
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data
    depends_on:
      - backend
    restart: unless-stopped
    command: ["python", "-m", "app.tg.bot"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
